initialize

diff --git a/TemplateModulLatex/Makefile b/TemplateModulLatex/Makefile
--- a/TemplateModulLatex/Makefile
+++ b/TemplateModulLatex/Makefile
@@ -1,3 +1,5 @@
+LATEX ?= xelatex
+
 define check_build_folder
 	@if [ ! -d $(1) ]; then mkdir -p $(1); fi
 endef
@@ -5,7 +7,7 @@ endef
 full:
 	@$(call check_build_folder, build)
 	@echo "Full build"
-	pdflatex -synctex=1 -jobname="full" full.tex
+	$(LATEX) -synctex=1 -jobname="full" full.tex
 	rm -f *.aux *.log *.out *.synctex.gz
 	mv full.pdf build/
 	@echo "Full build done"
@@ -17,17 +19,32 @@ build-module:
 	@echo "Build Partial Module"
 	@if [ -z "$(module)" ]; then \
 		echo "Error: Module are not set"; \
-		echo "Usage: make module module=3"; \
+		echo "Usage: make build-module module=3"; \
 		exit 1; \
 	fi
 	@if [ ! -f "materi/pertemuan$(module).tex" ]; then \
 		echo "Error: Materi for module $(module) does not exist"; \
 		exit 1; \
 	fi
-	pdflatex -synctex=1 -jobname="pertemuan$(module)" "\def\modulenumber{$(module)} \input{module.tex}"
+	$(LATEX) -synctex=1 -jobname="pertemuan$(module)" "\def\modulenumber{$(module)} \input{module.tex}"
 	rm -f *.aux *.log *.out *.synctex.gz
 	mv "pertemuan$(module).pdf" build/
 
+build-general:
+	@$(call check_build_folder, build)
+	@echo "Build Partial Module"
+	@if [ -z "$(module)" ]; then \
+		echo "Error: Module are not set"; \
+		echo "Usage: make build-module module=$(module)"; \
+		exit 1; \
+	fi
+	@if [ ! -f "materi/$(module).tex" ]; then \
+		echo "Error: Materi for module $(module) does not exist"; \
+		exit 1; \
+	fi
+	$(LATEX) -synctex=1 -jobname="$(module)" "\def\modulenumber{$(module)} \input{module.tex}"
+	rm -f *.aux *.log *.out *.synctex.gz
+	mv "$(module).pdf" build/
 
 module-all:
 	@$(call check_build_folder, build)
@@ -37,7 +54,7 @@ module-all:
 		if [ -f "$$file" ]; then \
 			count=$$((count + 1)); \
 			echo "Building module $$count"; \
-			pdflatex -synctex=1 -jobname="pertemuan$$count" "\def\modulenumber{$$count} \input{module.tex}" ; \
+			$(LATEX) -synctex=1 -jobname="pertemuan$$count" "\def\modulenumber{$$count} \input{module.tex}" ; \
 		fi \
 	done
 	rm -f *.aux *.log *.out *.synctex.gz
@@ -47,7 +64,7 @@ new-module:
 	@echo "Create new materi"
 	@if [ -z "$(module)" ]; then \
 		echo "Error: Module are not set"; \
-		echo "Usage: make new-materi module=3"; \
+		echo "Usage: make new-module module=3"; \
 		exit 1; \
 	fi
 	@if [ -f "materi/pertemuan$(module).tex" ]; then \
@@ -56,13 +73,18 @@ new-module:
 	fi
 	@echo "Create new materi for module $(module)"
 	@echo "\begin{center}" >> materi/pertemuan$(module).tex
-	@echo -e "\\\textbf{Modul $(module) Praktikum [MATA KULIAH PRAKTIKUM]}\n" >> materi/pertemuan$(module).tex
+	@echo -e "\\\textbf{Modul $(module) Praktikum \matakuliah}\n" >> materi/pertemuan$(module).tex
 	@echo "\textbf{JUDUL MATERI}" >> materi/pertemuan$(module).tex
-	@echo "\end{center}" >> materi/pertemuan$(module).tex	
+	@echo "\end{center}" >> materi/pertemuan$(module).tex
 
 build-tugas:
 	@echo "Build Tugas"
-	pdflatex -synctex=1 -jobname="tugas$(tugas)" "\def\tugasnumber{$(tugas)} \input{tugas.tex}"
+	@if [ -z "$(tugas)" ]; then \
+		echo "Error: Tugas are not set"; \
+		echo "Usage: make build-tugas tugas=3"; \
+		exit 1; \
+	fi
+	$(LATEX) -synctex=1 -jobname="tugas$(tugas)" "\def\tugasnumber{$(tugas)} \input{tugas.tex}"
 	rm -f *.aux *.log *.out *.synctex.gz
 	mv "tugas$(tugas).pdf" build/
 
@@ -73,7 +95,7 @@ tugas-all:
 		if [ -f "$$file" ]; then \
 			count=$$((count + 1)); \
 			echo "Building tugas $$count"; \
-			pdflatex -synctex=1 -jobname="tugas$$count" "\def\tugasnumber{$$count} \input{tugas.tex}" ; \
+			$(LATEX) -synctex=1 -jobname="tugas$$count" "\def\tugasnumber{$$count} \input{tugas.tex}" ; \
 		fi \
 	done
 	rm -f *.aux *.log *.out *.synctex.gz
@@ -99,6 +121,3 @@ new-tugas:
 clean:
 	@echo "Clean build files"
 	rm -rf build/*
-
-
-	
